version: '2.1'
services:
  web:
    image: lll
    links:
      - mysql
    environment:
      WORDPRESS_DB_PASSWORD: radioboot
    working_dir: /var/www/html
    volumes_from:
      - data
    volumes:
      - ./wordpress/wp-content/:/var/www/html/wp-content
    ports:
      - "80:80"
  mysql:
    image: mysql:5.7
    volumes_from:
      - data
    environment:
      MYSQL_ROOT_PASSWORD: radioboot
  data:
    image: busybox
    volumes:
      - /var/www/html/wp-content
      - /var/lib/mysql
