version: '2'
services:
  web:
    image: lxsameer/radioboot:v0.1.2
    links:
      - mysql
    environment:
      WORDPRESS_DB_PASSWORD: radioboot
      WORDPRESS_DB_HOST: mysql
    working_dir: /var/www/html
    volumes_from:
      - data
    depends_on:
      - mysql
    ports:
      - "80:80"
  mysql:
    image: mysql:5.7
    volumes_from:
      - data
    environment:
      MYSQL_ROOT_PASSWORD: radioboot
  data:
    image: busybox
    volumes:
      - /var/lib/mysql
